import type { Config } from "tailwindcss";

const config = {

  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
      },
  
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "sunglow-50": "#fffaef",
        "sunglow-100": "#fef0ce",
        "sunglow-200": "#fee8b6",
        "sunglow-300": "#fede95",
        "sunglow-400": "#fdd781",
        "sunglow-500": "#fdcd61",
        "sunglow-600": "#e6bb58",
        "sunglow-700": "#b49245",
        "sunglow-800": "#8b7135",
        "sunglow-900": "#6a5629",
        "jet-50": "#ebebeb",
        "jet-100": "#c1c0c1",
        "jet-200": "#a3a2a3",
        "jet-300": "#787779",
        "jet-400": "#5e5d5f",
        "jet-500": "#363437",
        "jet-600": "#312f32",
        "jet-700": "#262527",
        "jet-800": "#1e1d1e",
        "jet-900": "#171617",
        "jasmine-50": "#fffbf3",
        "jasmine-100": "#fff4d9",
        "jasmine-200": "#ffeec7",
        "jasmine-300": "#ffe6ad",
        "jasmine-400": "#ffe19d",
        "jasmine-500": "#ffda85",
        "jasmine-600": "#e8c679",
        "jasmine-700": "#b59b5e",
        "jasmine-800": "#8c7849",
        "jasmine-900": "#6b5c38",
        "eirie-50": "#e8e8e8",
        "eirie-100": "#b8b8b9",
        "eirie-200": "#969697",
        "eirie-300": "#666667",
        "eirie-400": "#484949",
        "eirie-500": "#1a1b1c",
        "eirie-600": "#181919",
        "eirie-700": "#121314",
        "eirie-800": "#0e0f0f",
        "eirie-900": "#0b0b0c",
        "neutrals-1": "#ffffff",
        "neutrals-2": "#fdfdfd",
        "neutrals-3": "#f6f6f6",
        "neutrals-4": "#f1f1f1",
        "neutrals-5": "#dddddd",
        "neutrals-6": "#c6c6c6",
        "neutrals-7": "#989899",
        "neutrals-8": "#6a6b6b",
        "neutrals-9": "#585959",
        "neutrals-10": "#3c3d3e",
        "neutrals-11": "#353637",
        "neutrals-12": "#2c2d2e",
        "neutrals-13": "#1a1b1c",
        "french-50": "#f9f8f9",
        "french-100": "#eceaeb",
        "french-200": "#e2e0e1",
        "french-300": "#d5d1d3",
        "french-400": "#cdc9cb",
        "french-500": "#c1bbbe",
        "french-600": "#b0aaad",
        "french-700": "#898587",
        "french-800": "#6a6769",
        "french-900": "#514f50",
        "brand-jasmine": "#ffda85",
        "brand-jet": "#363437",
        "brand-sunglow": "#fdcd61",
        "brand-eirie": "#1a1b1c",
        "brand-french": "#c1bbbe",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontSize: {
        'cursorIcon': '0.75em',
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
